name: subpixal
channels:
    - http://ssb.stsci.edu/astroconda
    - conda-forge
dependencies:
    - python>=3.5
    - setuptools
    - numpy
    - numpydoc
    - scipy
    - astropy>=3.1
    - drizzlepac
    - graphviz
    - matplotlib
    - sphinx
    - pip:
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx_automodapi
      - stsci.tools
      - stsci.skypac
      - stwcs
