name: subpixal
channels:
    - defaults
dependencies:
    - "python>=3.5"
    - setuptools
    - "numpy>=1.15.1"
    - numpydoc
    - scipy
    - "astropy>=3.1"
    - drizzlepac
    - graphviz
    - matplotlib
    - sphinx
    - "tweakwcs>=0.4.2"
    - pip:
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx_automodapi
      - stsci.tools
      - stsci.skypac
      - stwcs
