name: subpixal
channels:
    - http://ssb.stsci.edu/astroconda
dependencies:
    - numpy
    - numpydoc
    - astropy
    - stsci
    - stwcs
    - drizzlepac
    - fitsblender
    - graphviz
    - matplotlib
    - scipy
    - sphinx
    - pip:
        - git+https://github.com/spacetelescope/stsci_rtd_theme.git#egg=stsci_rtd_theme
